### ISSUE TITLE
Problem in Emphasized bars on 4HM

### ISSUE THREAD

**Issue by PeTeFIN** [BigWigsMods/BigWigs_Classic#10]
In NAXX 4HM fight, the bars for marks you get in the fight wont go away after the timer is finished. So at the end of the fight you have something like 30 bars high tower.

![image](https://github.com/BigWigsMods/BigWigs_Classic/assets/29127746/46331eec-50cc-4959-8b88-f0f4f3872517)

**Comment by funkydude** [comment]
Fixed, thanks for reporting!
